// File generated by FlutterFire CLI.
// Run: flutterfire configure
// This file will be auto-generated when you run `flutterfire configure`
// Replace this file with the generated one from your Firebase project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⚠️ REPLACE THESE VALUES with your actual Firebase project config
  // Run: flutterfire configure --project=YOUR_PROJECT_ID

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdtkDVFk75nMmnFJ49KbXWs36tQiIPtHc',
    appId: '1:673386890547:web:00253f68a2033b24fdaa46',
    messagingSenderId: '673386890547',
    projectId: 'rescue-mini-project-6ceb6',
    authDomain: 'rescue-mini-project-6ceb6.firebaseapp.com',
    storageBucket: 'rescue-mini-project-6ceb6.firebasestorage.app',
    measurementId: 'G-PX7XX2HF98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwjm8GuvZxqU56ZQUQNEK8cx_1TbH643M',
    appId: '1:673386890547:android:e1a4c177ed398976fdaa46',
    messagingSenderId: '673386890547',
    projectId: 'rescue-mini-project-6ceb6',
    storageBucket: 'rescue-mini-project-6ceb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMR5TP7Dy1Wq3oOu_j2xbGe9RCq1NJfLc',
    appId: '1:673386890547:ios:67e3ea39cca8eb14fdaa46',
    messagingSenderId: '673386890547',
    projectId: 'rescue-mini-project-6ceb6',
    storageBucket: 'rescue-mini-project-6ceb6.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMR5TP7Dy1Wq3oOu_j2xbGe9RCq1NJfLc',
    appId: '1:673386890547:ios:67e3ea39cca8eb14fdaa46',
    messagingSenderId: '673386890547',
    projectId: 'rescue-mini-project-6ceb6',
    storageBucket: 'rescue-mini-project-6ceb6.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdtkDVFk75nMmnFJ49KbXWs36tQiIPtHc',
    appId: '1:673386890547:web:9effb4ad8ba2e8eefdaa46',
    messagingSenderId: '673386890547',
    projectId: 'rescue-mini-project-6ceb6',
    authDomain: 'rescue-mini-project-6ceb6.firebaseapp.com',
    storageBucket: 'rescue-mini-project-6ceb6.firebasestorage.app',
    measurementId: 'G-KXDMK49WK4',
  );

}